# Site settings
title: RSDesign
email: rei@rsdesign.llc.com
description: Transforming ideas into reality with creative design and <br/>cutting-edge digital solutions.At RSDesign, LLC, we bring your vision<br/>  to life with our expertise in visual design and development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Denver
state: CO
zip_code: 80129
country: United States of America
phone: 

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed